# Generated by Django 4.2.16 on 2024-09-17 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(name="UserProfile",),
    ]
